# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(262, 252)
        self.centralwidget = QtWidgets.QWidget(LoginPage)
        self.centralwidget.setObjectName("centralwidget")
        self.accountText = QtWidgets.QLineEdit(self.centralwidget)
        self.accountText.setGeometry(QtCore.QRect(100, 70, 111, 21))
        self.accountText.setObjectName("accountText")
        self.passwordText = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordText.setGeometry(QtCore.QRect(100, 110, 111, 21))
        self.passwordText.setObjectName("passwordText")
        self.passwordText.setEchoMode(QtWidgets.QLineEdit.Password)
        self.codeText = QtWidgets.QLineEdit(self.centralwidget)
        self.codeText.setGeometry(QtCore.QRect(100, 150, 111, 21))
        self.codeText.setObjectName("codeText")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(30, 200, 75, 23))
        self.confirmButton.setObjectName("confirmButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(160, 200, 75, 23))
        self.exitButton.setObjectName("exitButton")
        self.accLabel = QtWidgets.QLabel(self.centralwidget)
        self.accLabel.setGeometry(QtCore.QRect(40, 70, 61, 20))
        self.accLabel.setObjectName("accLabel")
        self.passLabel = QtWidgets.QLabel(self.centralwidget)
        self.passLabel.setGeometry(QtCore.QRect(40, 110, 61, 20))
        self.passLabel.setObjectName("passLabel")
        self.codeLabel = QtWidgets.QLabel(self.centralwidget)
        self.codeLabel.setGeometry(QtCore.QRect(40, 150, 61, 20))
        self.codeLabel.setObjectName("codeLabel")
        self.platformBox = QtWidgets.QComboBox(self.centralwidget)
        self.platformBox.setGeometry(QtCore.QRect(110, 30, 69, 22))
        self.platformBox.setObjectName("platformBox")
        self.platformBox.addItem("")
        self.platformBox.addItem("")
        self.platformBox.addItem("")
        self.platformText = QtWidgets.QLabel(self.centralwidget)
        self.platformText.setGeometry(QtCore.QRect(70, 30, 41, 20))
        self.platformText.setObjectName("platformText")
        self.Author = QtWidgets.QLabel(self.centralwidget)
        self.Author.setGeometry(QtCore.QRect(190, 0, 81, 16))
        self.Author.setObjectName("Author")
        self.VersionText = QtWidgets.QLabel(self.centralwidget)
        self.VersionText.setGeometry(QtCore.QRect(0, 0, 101, 20))
        self.VersionText.setObjectName("VersionText")
        LoginPage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginPage)
        self.statusbar.setObjectName("statusbar")
        LoginPage.setStatusBar(self.statusbar)

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "登入界面"))
        self.confirmButton.setText(_translate("LoginPage", "确认"))
        self.exitButton.setText(_translate("LoginPage", "退出"))
        self.accLabel.setText(_translate("LoginPage", "账号："))
        self.passLabel.setText(_translate("LoginPage", "密码："))
        self.codeLabel.setText(_translate("LoginPage", "验证码："))
        self.platformBox.setItemText(0, _translate("MainWindow", "请选择"))
        self.platformBox.setItemText(1, _translate("MainWindow", "BB"))
        self.platformBox.setItemText(2, _translate("MainWindow", "ML"))
        self.platformText.setText(_translate("LoginPage", "平台："))
        self.Author.setText(_translate("LoginPage", "Author：Din"))
        self.VersionText.setText(_translate("LoginPage", "Version：1.0-beta"))

